server:
  port: 8080

spring:
  application:
    name: bookapp
  config:
    import: optional:file:.env[.properties]

  # [개발용 H2 설정] (현재 활성화 상태)
  # datasource:
  #   driver-class-name: org.h2.Driver
  #   url: jdbc:h2:mem:bookdb
  #   username: sa
  #   password: 1234
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console
  # jpa:
  #   hibernate:
  #     ddl-auto: create
  #   show-sql: true

  # [배포 및 Aiven MySQL 설정] (Aiven이 Running이 되면 아래 주석을 풀고 위의 H2 설정을 주석처리하세요)
  datasource:
    driver-class-name: ${MYSQL_DRIVER_CLASS_NAME}
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
